baseurl = "https://math.miyatani.org/"
title = "Kazuaki MIYATANI"
theme = "mathweb"

disableKinds = ['taxonomy', 'term', 'sitemap']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    weight = 1
