baseurl = "/"
title = "Kazuaki MIYATANI"
theme = "mathweb"

disableKinds = ['taxonomy', 'term']

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

[languages]
  [languages.en]
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
